train:
  - _target_: src.datasets.LibrispeechDataset
    part: "train-clean-100"
    max_audio_length: 16.7
    instance_transforms: ${transforms.instance_transforms.train}
  - _target_: src.datasets.LibrispeechDataset
    part: "train-clean-360"
    max_audio_length: 16.7
    instance_transforms: ${transforms.instance_transforms.train}
  - _target_: src.datasets.LibrispeechDataset
    part: "train-other-500"
    max_audio_length: 16.7
    instance_transforms: ${transforms.instance_transforms.train}
val_clean:
  - _target_: src.datasets.LibrispeechDataset
    part: "test-other"
    instance_transforms: ${transforms.instance_transforms.inference}
val_other:
  - _target_: src.datasets.LibrispeechDataset
    part: "test-other"
    instance_transforms: ${transforms.instance_transforms.inference}
