train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.SpecAugment
        freq_masks: 2
        time_masks: 6
        freq_width: 27
        time_width: 64

inference: null
