_target_: src.model.Conformer
dropout: 0.1
n_mels: 80
num_blocks: 2
conv_sub_params:
  in_channels: 1
  out_channels: ${..conformer_block_params.msha_params.embed_dim}
  kernel_size: 3
  stride: 2
  padding: 1
conformer_block_params:
  ff_params:
    expansion_factor: 4
    dropout: 0.1
  msha_params:
    max_rel_pos: 256
    embed_dim: 176
    num_heads: 4
    dropout: 0.1
  conv_params:
    kernel_size: 31
    dropout: 0.1
