_target_: src.model.Conformer
n_tokens: null
num_blocks: 1
n_mels: 80
dropout: 0.1
conv_sub_params:
  in_channels: 1
  out_channels: ${..conformer_block_params.msha_params.embed_dim}
  kernel_size: 3
  stride: 2
  padding: 1
conformer_block_params:
  ff_params:
    expansion_factor: 4
    dropout: 0.1
  msha_params:
    max_rel_pos: 16
    embed_dim: 16
    num_heads: 1
    dropout: 0.1
  conv_params:
    kernel_size: 3
    dropout: 0.1
