defaults:
  - model: conformer
  - metrics: asr_metrics
  - datasets: test_other
  - dataloader: example
  - transforms: example
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoderWithBeamSearch
  beam_width: 20
  num_workers: 8
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference_result" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "conformer/model_best.pth" # path to the pretrained model
