_target_: src.logger.WandBWriter
project_name: "asr"
entity: "hse_university"
run_name: "testing"
mode: "disabled"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
